// File generated by FlutterFire CLI / Firebase tools.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCde3J8TYZNlxwEPoRHdkcT23HAMHTK2Ho',
    appId: '1:491331899335:web:669d7416815b6cff1b13e2',
    messagingSenderId: '491331899335',
    projectId: 'civicconnect-defca',
    authDomain: 'civicconnect-defca.firebaseapp.com',
    storageBucket: 'civicconnect-defca.firebasestorage.app',
    measurementId: 'G-SMK45YX6FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqqvzCaNoP7GPz19eBmDAFmpCoLmJps_Q',
    appId: '1:491331899335:android:2c95b13e43f6f71a1b13e2',
    messagingSenderId: '491331899335',
    projectId: 'civicconnect-defca',
    storageBucket: 'civicconnect-defca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqvzCaNoP7GPz19eBmDAFmpCoLmJps_Q',
    appId: '1:491331899335:android:2c95b13e43f6f71a1b13e2',
    messagingSenderId: '491331899335',
    projectId: 'civicconnect-defca',
    storageBucket: 'civicconnect-defca.firebasestorage.app',
  );
}
